# Generated by Django 5.0 on 2024-03-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fueldrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitefixed',
            name='global_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='global ID'),
        ),
    ]
