# Generated by Django 5.0 on 2024-02-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fueldrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyfuel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
