# Generated by Django 5.0 on 2024-03-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sitefixed_global_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyfuel',
            name='Tasks',
            field=models.CharField(choices=[('Diesel Filling and Energy Reading', 'Diesel Filling and Energy Reading'), ('Energy Reading', 'Energy Reading')], max_length=200, verbose_name='Tasks'),
        ),
    ]
