# Generated by Django 5.0 on 2024-03-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fueldrawn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyfuel',
            name='Date_Of_Diesel_Filling',
            field=models.DateTimeField(verbose_name='Date of Diesel Filling'),
        ),
    ]
