# Generated by Django 5.0 on 2024-03-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_energyfuel_date_of_diesel_filling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyfuel',
            name='DG_HMR_Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=30, verbose_name='DG HMR Status'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='DG_PIU_Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=30, verbose_name='DG PIU Status'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='Date_Of_Diesel_Filling',
            field=models.DateField(verbose_name='Date of Diesel Filling'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='EB_Meter_Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=30, verbose_name='EB Meter Status'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='EB_PIU_Meter_Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=30, verbose_name='EB PIU Meter Status'),
        ),
    ]
