# Generated by Django 5.0 on 2024-03-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_energyfuel_dg_hmr_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyfuel',
            name='Current_DG_PIU_Reading',
            field=models.IntegerField(null=True, verbose_name='Current DG PIU Reading'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='Current_Diesel_Balance',
            field=models.IntegerField(null=True, verbose_name='Current Diesel Balance'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='Current_EB_MTR_KWH',
            field=models.IntegerField(null=True, verbose_name='Current EB MTR (KWH)'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='Current_EB_PIU_Reading',
            field=models.IntegerField(null=True, verbose_name='Current EB PIU Reading'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='DG_HMR_Reading',
            field=models.IntegerField(null=True, verbose_name='DG HMR Reading'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='DG_HMR_Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=30, null=True, verbose_name='DG HMR Status'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='DG_PIU_Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=30, null=True, verbose_name='DG PIU Status'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='DG_Running_Hours_Reading_Image',
            field=models.ImageField(null=True, upload_to='DG Running Hours Reading (As Per HMR Meter)/%y', verbose_name='DG Running Hours Reading (As Per HMR Meter) Image'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='DG_Running_Hours_as_per_piu_Reading_Image',
            field=models.ImageField(null=True, upload_to='DG Running Hours Reading (As Per PIU/12PMS/AMF)/%y', verbose_name='DG Running Hours Reading (As Per PIU/12PMS/AMF) Image'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='Date_Of_Diesel_Filling',
            field=models.DateField(null=True, verbose_name='Date of Diesel Filling'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='Diesel_Balance_Before_Filling',
            field=models.IntegerField(null=True, verbose_name='Diesel Balance Before Filling'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='Diesel_Bill_Number_Image',
            field=models.ImageField(null=True, upload_to='Diesel Bill Number/%y', verbose_name='Diesel Bill Number Image'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='Diesel_Filling_Done',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True, verbose_name='Diesel Filling Done'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='EB_Cumulative_KWH_Image',
            field=models.ImageField(null=True, upload_to='EB Cumulative KWH (As Per EB Meter)/%y', verbose_name='EB Cumulative KWH (As Per EB Meter) Image'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='EB_Meter_Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=30, null=True, verbose_name='EB Meter Status'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='EB_PIU_Meter_Status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not-Available', 'Not-Available')], max_length=30, null=True, verbose_name='EB PIU Meter Status'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='EB_Running_Hours_Cumulative_Image',
            field=models.ImageField(null=True, upload_to='EB Cumulative KWH (As Per EB Meter)/%y', verbose_name='EB Cumulative KWH (As Per EB Meter) Image'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='FT_ID',
            field=models.CharField(max_length=50, null=True, verbose_name='FT ID'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='FT_name',
            field=models.CharField(max_length=200, null=True, verbose_name='FT Name'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='Fuel_Qty_Filled',
            field=models.IntegerField(null=True, verbose_name='Fuel Qty. Filled'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='Remarks',
            field=models.TextField(null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='Total_DC_Load',
            field=models.IntegerField(null=True, verbose_name='Total DC Load'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='Total_EB_KWH_Reading_from_all_Channels',
            field=models.IntegerField(null=True, verbose_name='Total EB KWH Reading from all channels'),
        ),
    ]
