# Generated by Django 5.0 on 2024-03-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_energyfuel_current_dg_piu_reading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyfuel',
            name='Date_Of_Diesel_Filling',
            field=models.DateTimeField(null=True, verbose_name='Date of Diesel Filling'),
        ),
    ]
