# Generated by Django 5.0 on 2024-03-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_energyfuel_date_of_diesel_filling'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyfuel',
            name='Time_Of_Diesel_Filling',
            field=models.TimeField(null=True, verbose_name='Time of Diesel Filling'),
        ),
        migrations.AlterField(
            model_name='energyfuel',
            name='Date_Of_Diesel_Filling',
            field=models.DateField(null=True, verbose_name='Date of Diesel Filling'),
        ),
    ]
